apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: cce-demo
type: Opaque
stringData:
  mysql-root-password: cce-demo-password
  mysql-user: cceuser
  mysql-password: cceuser-password
