{{- if eq .Values.fileStorage.mountType "obs" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.fileStorage.obs.pvcName }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    everest.io/obs-volume-type: "{{ .Values.fileStorage.obs.volumeType }}"
    {{- if .Values.fileStorage.obs.volumeNamePrefix }}
    everest.io/csi.volume-name-prefix: "{{ .Values.fileStorage.obs.volumeNamePrefix }}"
    {{- end }}
    {{- if .Values.fileStorage.obs.storageClass.parameters }}
    {{- range $key, $value := .Values.fileStorage.obs.storageClass.parameters }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    {{- end }}
    csi.storage.k8s.io/node-publish-secret-name: {{ .Values.fileStorage.obs.secretName }}
    csi.storage.k8s.io/node-publish-secret-namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.fileStorage.obs.capacity }}
  storageClassName: csi-obs
---
{{- end }}
