apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword }}
  mysql-user: {{ .Values.mysql.auth.username }}
  mysql-password: {{ .Values.mysql.auth.password }}
