{{- if eq .Values.fileStorage.mountType "obs" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fileStorage.obs.secretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    secret.kubernetes.io/used-by: csi
type: cfe/secure-opaque
data:
  access.key: {{ .Values.fileStorage.obs.accessKey | b64enc }}
  secret.key: {{ .Values.fileStorage.obs.secretKey | b64enc }}
{{- end }}
