{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: {{ .Values.backend.service.port }}
    targetPort: 8080
  type: {{ .Values.backend.service.type }}
{{- end }}
