{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.service.port }}
    targetPort: 80
  type: {{ .Values.frontend.service.type }}
{{- end }}
